---
name: Larger region error report
description: Report errors in the hg002v1.1 assembly which span more than 50 base pairs
title: Larger localized issue in the hg002v1.1 assembly
labels: ["v1.1","large_error"]
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to share your observations about the HG002 v1.1 Q100 assembly. Before submitting an issue, please check to be sure it isn't already in our BED track of issues that are already scheduled to be applied, or our BED track of submitted issues to be evaluated. Both of these sets of regions are displayed as tracks in our UCSC browser assembly hub [here](http://genome.ucsc.edu/cgi-bin/hgHubConnect?hgHub_do_redirect=on&hgHubConnect.remakeTrackHub=on&hgHub_do_firstDb=1&hubUrl=https://research.nhgri.nih.gov/CustomTracks/T2T_hubs/HG002_Q100/hub.txt). 
- type: checkboxes
  id: checkedexisting
  attributes:
    label: Have you confirmed that this issue hasn't already been reported?
    options:
      - label: I have confirmed in the UCSC browser hub that this is a new issue (required)
        required: true
- type: input
  id: Region
  attributes:
    label: "Issue location in assembly (use format chromosome:start-end, e.g., chr13_MATERNAL:3740148-9625296)"
- type: textarea
  id: issuedescription
  attributes:
    label: Description of the issue
    description: "Please provide as much detail as possible. What evidence is there that the assembly is wrong here?"
  validations:
    required: true
---
